title: <p align="center"> Chaitanya Swaroop Juturi </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sajan-kedia-b06a6821/">LinkedIn</a> |
  <a href="https://github.com/chaitanyakvs">GitHub</a>
  
  <br>   
  I'm working on Embedded Software, Internet Of Things related problems.
  Also handing the Artificial Intelligence and Machine Learning based Research in Mobile Platform.
  Working in Thundersoft India in Multimedia Team.
 
  <br>
  </p>



theme: jekyll-theme-minimal
